## [Deep Learning With Pytorch: A 60 Minute BLITZ (By Official Pytorch Documentation)](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)

In [57]:
import torch

In [58]:
# Initialize an Empty Tensor
X=torch.empty(5,3)

An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

In [59]:
print(X)

tensor([[-1.5463e+01,  3.0673e-41, -1.7284e-31],
        [ 4.5692e-41,  8.9683e-44,  0.0000e+00],
        [ 1.1210e-43,  0.0000e+00, -1.5463e+01],
        [ 3.0673e-41,  1.5975e-43,  1.6115e-43],
        [ 4.4842e-44,  8.5479e-44,  4.4842e-44]])


In [60]:
# Create a Random Tensor Of Any shape
Y=torch.rand(1,2)

In [61]:
print('Tensor:',Y)
print('Shape of the Tensor:',Y.shape)


Tensor: tensor([[0.2147, 0.4041]])
Shape of the Tensor: torch.Size([1, 2])


In [62]:
#Example 2
Y1=torch.rand(5,3)
print('Tensor:',Y1)
print('Shape of the Tensor:',Y1.shape)

Tensor: tensor([[0.0237, 0.6009, 0.7549],
        [0.9086, 0.9635, 0.4818],
        [0.7021, 0.8204, 0.8384],
        [0.6822, 0.2597, 0.1903],
        [0.3198, 0.3554, 0.3502]])
Shape of the Tensor: torch.Size([5, 3])


In [63]:
# Matrix Filled with Zeros and Ones
#Zeros
Zero_Matrix=torch.zeros((5,5))
#Zero_Matrix=torch.zeros(5,3,dtype=torch.lon)

In [64]:
print('Tensor:',Zero_Matrix)
print('Shape of the Tensor:',Zero_Matrix.shape)

Tensor: tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Shape of the Tensor: torch.Size([5, 5])


In [65]:
#ones
Ones_Matrix=torch.ones(5,3,dtype=torch.long)

In [66]:
print('Tensor:',Ones_Matrix)
print('Shape of the Tensor:',Ones_Matrix.shape)

Tensor: tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
Shape of the Tensor: torch.Size([5, 3])


In [67]:
Ones_Matrix.size()

torch.Size([5, 3])

## Operations

#Addition
If you have a one element tensor, use .item() to get the value as a Python number

In [68]:
a=torch.rand(1)

In [69]:
a

tensor([0.8157])

In [70]:
a.item()

0.8157070875167847

In [71]:
#A Tensor
type(a)

torch.Tensor

In [72]:
#Tensor to Numpy 
b=a.numpy()

In [73]:
b

array([0.8157071], dtype=float32)

In [74]:
type(b)

numpy.ndarray

In [75]:
#Numpy to Tensor
c=torch.from_numpy(b)

In [76]:
c

tensor([0.8157])

In [77]:
type(c)

torch.Tensor

## [AUTOGRAD: AUTOMATIC DIFFERENTIATION](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html)

In [78]:
import torch

In [79]:
X=torch.rand(2,2,requires_grad=True)

In [80]:
X

tensor([[0.3598, 0.4603],
        [0.2096, 0.5841]], requires_grad=True)

In [81]:
Y=2*X*X

In [82]:
Y


tensor([[0.2589, 0.4238],
        [0.0878, 0.6824]], grad_fn=<MulBackward0>)

In [83]:
Y.grad_fn

In [84]:
z=Y*Y

In [85]:
z

tensor([[0.0670, 0.1796],
        [0.0077, 0.4657]], grad_fn=<MulBackward0>)

In [86]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [87]:
out=z.mean()

In [88]:
out

tensor(0.1800, grad_fn=<MeanBackward0>)

In [89]:
out.backward()

## [Neural Networks](https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html)

## [Training A Classifier](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html)