## DATA IN NUMPY


### Scalars

In [1]:
import numpy as np

In [2]:
#Scalars in Numpy
S=np.array(2)

In [3]:
type(S)

numpy.ndarray

In [4]:
#Shape of Scalar (Zero dimensional Vector is called as a Scalar)
S.shape

()

In [5]:
#Basic Arithmatgic Ops with Numpy Scalars is Possible (Similar to the Python Math Scalar Operations)
X=S+8

In [6]:
X

10

In [7]:
#type is always a Numpy  ndarray since we are working with Numpy array types ( not with the python types)

type(X)

numpy.int64

In [8]:
X.shape

()

In [14]:
#Scalars does not have any Dimensions
X.ndim

0

### Vectors

In [15]:
# Vectors are 1 Dimensional (Simlar to that of Lists in Python)
V=np.array([1,2,3,4])

In [16]:
type(V)

numpy.ndarray

In [17]:
#1 Dimensional Shape
V.shape

(4,)

In [18]:
# Shows the Number of Dimensions
V.ndim

1

### Slicind and Indexing  (Important operations performed on the Numpy arrays)

In [19]:
#Example of Indexing
V[0]

1

In [20]:
V[1]

2

In [22]:
#Example of Slicing[start:stop:step]
V[:]

array([1, 2, 3, 4])

In [23]:
V[::]

array([1, 2, 3, 4])

In [24]:
V[1:]

array([2, 3, 4])

In [25]:
V[:2]

array([1, 2])

In [26]:
V[::-1]

array([4, 3, 2, 1])

In [28]:
#Negative Indexing and slicing 
V[-1]

4

In [33]:
V[-1:]

array([4])

#### To Learn More about Advanced Slicing and Indexing Operation on the numpy Arrays Visit the Below Link
[Advanced Indexing and Slicing in Numpy (Original Numpy Documentaion)](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)

## Matrices

In [35]:
#Matrices are just a List of Lists or 2 Dimensional Vectors
M=np.array([[1,2,3],[4,3,5]])

In [36]:
M

array([[1, 2, 3],
       [4, 3, 5]])

In [37]:
type(M)

numpy.ndarray

In [38]:
#shape of a Matrix (2D)
M.shape

(2, 3)

In [39]:
M.ndim

2

In [42]:
#matrices indexing ( Example to get the number 5 from the matrix)
M[1][2]

5

## Tensors

Tensors are just like vectors and matrices, but they can have more dimensions. For example, to create a 3x3x2x1 tensor, you could do the following:

In [43]:
T = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [44]:
T

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]],


       [[[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [17]]]])

In [45]:
type(T)

numpy.ndarray

In [46]:
T.shape

(3, 3, 2, 1)

## Reshape 

https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

In [49]:
V

array([1, 2, 3, 4])

In [50]:
V.shape

(4,)

In [51]:
V.reshape(1,4)

array([[1, 2, 3, 4]])

In [53]:
V.shape

(4,)

In [54]:
V.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [55]:
X=V[None,:]

In [56]:
X

array([[1, 2, 3, 4]])

In [57]:
X.shape

(1, 4)

In [58]:
X=V[:None,]

In [59]:
X

array([1, 2, 3, 4])

In [60]:
X.shape

(4,)

In [61]:
V

array([1, 2, 3, 4])

In [63]:
#Element wise Matrix Operations in Numpy
V+5

array([6, 7, 8, 9])

In [64]:
V-5

array([-4, -3, -2, -1])

In [65]:
V*2

array([2, 4, 6, 8])

In [66]:
V/255


array([0.00392157, 0.00784314, 0.01176471, 0.01568627])

In [68]:
a = np.array([[1,3],[5,7]])
a
# displays the following result:
# array([[1, 3],
#        [5, 7]])

b = np.array([[2,4],[6,8]])
b
# displays the following result:
# array([[2, 4],
#        [6, 8]])

a + b


array([[ 3,  7],
       [11, 15]])

In [69]:
a = np.array([[1,3],[5,7]])
a
# displays the following result:
# array([[1, 3],
#        [5, 7]])
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
c
# displays the following result:
# array([[2, 3, 6],
#        [4, 5, 9],
#        [1, 8, 7]])

a.shape
# displays the following result:
#  (2, 2)

c.shape
# displays the following result:
#  (3, 3)

a + c

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

### Numpy Matrix Multiplications

In [70]:
M1=np.array([[1,2,3],[3,21,1]])

In [71]:
M1

array([[ 1,  2,  3],
       [ 3, 21,  1]])

In [72]:
M1.shape

(2, 3)

In [73]:
M1*0.25

array([[0.25, 0.5 , 0.75],
       [0.75, 5.25, 0.25]])

In [74]:

M1*M1

array([[  1,   4,   9],
       [  9, 441,   1]])

In [76]:
# Since the number of coloumns in the Left matrix is not equal to the number of rows in the right Matrix
np.dot(M1,M1)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [78]:
M2=np.array([[1,2,3,4],[23,1,45,18],[12,1,2,1]])

In [79]:
M2

array([[ 1,  2,  3,  4],
       [23,  1, 45, 18],
       [12,  1,  2,  1]])

In [80]:
M2.shape

(3, 4)

In [81]:
#dot product is possible
M3=np.dot(M1,M2)

In [82]:
M3

array([[ 83,   7,  99,  43],
       [498,  28, 956, 391]])

In [83]:
M3_matmul=np.matmul(M1,M2)

In [84]:
M3_matmul

array([[ 83,   7,  99,  43],
       [498,  28, 956, 391]])

In [85]:
M1

array([[ 1,  2,  3],
       [ 3, 21,  1]])

In [86]:
M1.shape

(2, 3)

In [90]:
M1_Transpose=M1.transpose()

In [91]:
M1_Transpose

array([[ 1,  3],
       [ 2, 21],
       [ 3,  1]])

In [92]:
M1_Transpose.shape

(3, 2)

In [94]:
M1_Transpose.T

array([[ 1,  2,  3],
       [ 3, 21,  1]])

In [122]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    X_1=np.array(inputs)
    input_array =X_1[None,:]
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    x=np.min(input_array)
    y=input_array-x
    inputs_minus_min =y

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    X=np.max(inputs_minus_min)
    Y=inputs_minus_min/X
    inputs_div_max =Y

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    
    X1=m1.shape
    X2=m2.shape
    
    if X1[1]!=X2[0]:
        return False
    else:
        return np.dot(m1,m2)
    

def find_mean(values):
    return np.mean(values)
    



input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
False
Mean == 2.6666666666666665


In [123]:
# Use the numpy library
import numpy as np


######################################################
#
#      MESSAGE TO STUDENTS:
#
#  This file contains a solution to the coding quiz. Feel free
#  to look at it when you are stuck, but try to solve the
#   problem on your own first.
#
######################################################


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    # We can use NumPy's min function and element-wise division
    inputs_minus_min = input_array - np.min(input_array)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    # We can use NumPy's max function and element-wise division
    inputs_div_max = inputs_minus_min / np.max(inputs_minus_min)

    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # Check the shapes of the matrices m1 and m2. 
    # m1 and m2 will be ndarray objects.
    #
    # Return False if the shapes cannot be used for matrix
    # multiplication. You may not use a transpose
    if m1.shape[0] != m2.shape[1] and m1.shape[1] != m2.shape[0]:     
        return False

    # Have not returned False, so calculate the matrix product
    # of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if m1.shape[1] == m2.shape[0]:
        return np.matmul(m1, m2)        
    else:
        return np.matmul(m2, m1)        


def find_mean(values):
    # Return the average of the values in the given Python list
    # NumPy has a lot of helpful methods like this.
    return np.mean(values)

input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))


Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
