In [39]:
#creating Tensors with Pytorch
import torch

In [40]:
#creating a random tensor (here a 5X3 Matrix)
X=torch.rand(5,3)

In [41]:
X

tensor([[0.5209, 0.5932, 0.8797],
        [0.6286, 0.7653, 0.1132],
        [0.8559, 0.6721, 0.6267],
        [0.5691, 0.7437, 0.9592],
        [0.3887, 0.2214, 0.3742]])

In [42]:
#shape of the Tensor
X.shape

torch.Size([5, 3])

In [43]:
#so Basically pytorch is similar to that of the Numpy/scipy libraries (stacked up or built upon)
#type(X)
type(X)

torch.Tensor

## Sigmoid Activation Function Using Pytorch

In [44]:
def sigmoid_activation(x):
    a=torch.exp(-x)
    b=1+a
    return 1/b
   

In [45]:
torch.manual_seed(7)

In [46]:
#Features 
Features=torch.randn((1,5))

In [47]:
Features

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])

In [48]:
#Weights
weights=torch.randn_like(Features)


In [49]:
weights

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [50]:
#Bias
bias=torch.randn((1,1))

In [51]:
bias

tensor([[0.3177]])

In [52]:
#Shape of These Tensors
print('shape of the Features or Input Parameters:',Features.shape)
print('shape of weights:',weights.shape)
print('shape of the bias:',bias.shape)

shape of the Features or Input Parameters: torch.Size([1, 5])
shape of weights: torch.Size([1, 5])
shape of the bias: torch.Size([1, 1])


### Matrix shapes Does not match

In [53]:
#Matrix Multiplication( Number of cols in the left matrix shd  match with no of rows in the right matrix)
inputs_weights_mul=torch.matmul(Features,weights)

RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at /opt/conda/conda-bld/pytorch_1579022030672/work/aten/src/TH/generic/THTensorMath.cpp:136

### Methods to Change the Shape of the weights Matrix 

In [54]:
weights.reshape(5,1)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [55]:
weights

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [56]:
# Inplace Parameter (not yet used)
weights.view(5,1)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [57]:
inputs_weights_mul=torch.matmul(Features,weights.view(5,1))

In [58]:
inputs_weights_mul

tensor([[-1.9796]])

In [59]:
inputs_weights_mul_bias=inputs_weights_mul+bias

In [60]:
inputs_weights_mul_bias

tensor([[-1.6619]])

In [61]:
#output of the Neural Network
sigmoid_activation(inputs_weights_mul_bias)

tensor([[0.1595]])

### Multilayer Neural Networks

### Stack them up!

That's how you can calculate the output for a single neuron. The real power of this algorithm happens when you start stacking these individual units into layers and stacks of layers, into a network of neurons. The output of one layer of neurons becomes the input for the next layer. With multiple input units and output units, we now need to express the weights as a matrix.

<img src='assets/multilayer_diagram_weights.png' width=450px>

The first layer shown on the bottom here are the inputs, understandably called the **input layer**. The middle layer is called the **hidden layer**, and the final layer (on the right) is the **output layer**. We can express this network mathematically with matrices again and use matrix multiplication to get linear combinations for each unit in one operation. For example, the hidden layer ($h_1$ and $h_2$ here) can be calculated 

$$
\vec{h} = [h_1 \, h_2] = 
\begin{bmatrix}
x_1 \, x_2 \cdots \, x_n
\end{bmatrix}
\cdot 
\begin{bmatrix}
           w_{11} & w_{12} \\
           w_{21} &w_{22} \\
           \vdots &\vdots \\
           w_{n1} &w_{n2}
\end{bmatrix}
$$

The output for this small network is found by treating the hidden layer as inputs for the output unit. The network output is expressed simply

$$
y =  f_2 \! \left(\, f_1 \! \left(\vec{x} \, \mathbf{W_1}\right) \mathbf{W_2} \right)
$$

In [62]:
torch.manual_seed(7) #set Some random seed

In [63]:
Features1=torch.randn((1,3))

In [64]:
Features1

tensor([[-0.1468,  0.7861,  0.9468]])

In [65]:
Features1.shape

torch.Size([1, 3])

In [68]:
# Neural Network units
n_input=Features1.shape[1]
n_hidden=2
n_output=1

In [69]:
#input to hidden layer
w1=torch.randn(n_input,n_hidden)
#hidden to output layer
w2=torch.randn(n_hidden,n_output)

In [71]:
#bias terms
b1=torch.randn(1,n_hidden)
b2=torch.randn(1,n_output)

In [72]:
w1.shape

torch.Size([3, 2])

In [73]:
Features1.shape

torch.Size([1, 3])

In [74]:
input_w1=torch.matmul(Features1,w1)

In [75]:
input_w1

tensor([[ 0.6270, -0.3969]])

In [76]:
input_w1_b1=input_w1+b1

In [77]:
input_w1_b1

tensor([[ 0.7598, -0.2596]])

In [78]:
hidden_layer_output=sigmoid_activation(input_w1_b1)

In [79]:
hidden_layer_output

tensor([[0.6813, 0.4355]])

In [80]:
hidden_w2=torch.matmul(hidden_layer_output,w2)

In [81]:
hidden_w2

tensor([[-1.0078]])

In [82]:
hidden_w2_b2=hidden_w2+b2

In [83]:
hidden_w2_b2

tensor([[-0.7672]])

In [84]:
Final_output=sigmoid_activation(hidden_w2_b2)

In [85]:
Final_output


tensor([[0.3171]])